dist: bionic
language: node_js
node_js:
    - 10
    - 12
services:
    - docker
cache:
    bundler: true
    directories:
        - node_modules
        - .eslintcache
before_script:
    - if [[ -v "DOCKER_PASSWORD" ]]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
    - . ./travis/travis-functions.sh
    - log_env_variables
script:
    - npm pack
    - npm test
    - npm run doc
    - npm run coveralls-report
jobs:
    include:
        - stage: publish
          mame: github alpha pages
          script: /bin/bash travis/node-functions.sh node_push_github_pages
          if: branch = env(DEV_BRANCH) AND type != pull_request AND (commit_message != release OR env(RELEASE_BRANCH) != env(DEV_BRANCH))
        - name: alpha npm
          script: npm pack && /bin/bash travis/node-functions.sh node_publish_alpha
          if: branch = env(DEV_BRANCH) AND type != pull_request AND (commit_message != release OR env(RELEASE_BRANCH) != env(DEV_BRANCH))
        - stage: release
          name: release npm, tag and upgrade
          script: npm pack && /bin/bash travis/node-functions.sh node_release
          if: branch = env(RELEASE_BRANCH) AND type != pull_request AND (commit_message = release OR env(RELEASE_BRANCH) != env(DEV_BRANCH))
